In [25]:
import numpy as np
from scipy.spatial.distance import cdist
a = np.array([[1,2,3], [4,5,6], [7,8,9], [208,21,8], [35,36,37]])
b = np.array([[0,1,2], [4,5,6], [5,5,5]])
sim  = 1- cdist(a, b, metric = 'cosine')
print(sim)
max_sim = np.max(sim, axis = 1)
print(max_sim)
bottom_N = max_sim.argsort()
bottom_N[:3]

[[0.95618289 0.97463185 0.9258201 ]
 [0.86640023 1.         0.98692754]
 [0.83480969 0.99819089 0.99483201]
 [0.07909216 0.53654673 0.65404015]
 [0.78873821 0.99032815 0.9997429 ]]
[0.97463185 1.         0.99819089 0.65404015 0.9997429 ]


array([3, 0, 2])

In [6]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(a,b)

array([[0.95618289, 0.97612933],
       [0.86640023, 0.99996596]])

In [7]:
a.shape

(2, 3)

In [9]:
c = np.random.rand(300, 3)
d = np.random.rand(100, 3)

In [20]:
%timeit cosine_similarity(c,d)
%timeit 1- cdist(c,d, metric = 'cosine')

311 µs ± 696 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
111 µs ± 112 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [14]:
%%time
1- cdist(c,d, metric = 'cosine')

CPU times: user 373 µs, sys: 312 µs, total: 685 µs
Wall time: 499 µs


array([[0.96857469, 0.89196447, 0.81996217, ..., 0.94030458, 0.94218486,
        0.91037244],
       [0.79040324, 0.91820775, 0.99658649, ..., 0.94224561, 0.70795146,
        0.57297207],
       [0.78168442, 0.76796381, 0.89689578, ..., 0.8452626 , 0.71791316,
        0.73290649],
       ...,
       [0.8085224 , 0.97010227, 0.85249184, ..., 0.93128992, 0.75340127,
        0.49915316],
       [0.92723695, 0.75770649, 0.43657278, ..., 0.76114267, 0.96525924,
        0.9080158 ],
       [0.7394572 , 0.92975909, 0.97698808, ..., 0.9251869 , 0.65337341,
        0.45207162]])