In [1]:
import numpy as np
from scipy.spatial.distance import cdist
from sklearn.metrics.pairwise import cosine_similarity
a = np.array([[1,2,3], [4,5,6], [7,8,9], [208,21,8], [35,36,37]])
b = np.array([[0,1,2], [4,5,6], [5,5,5]])
sim  = 1- cdist(a, b, metric = 'cosine')
print(sim)
max_sim = np.max(sim, axis = 1)
print(max_sim)
bottom_N = max_sim.argsort()
bottom_N[:3]

[[0.95618289 0.97463185 0.9258201 ]
 [0.86640023 1.         0.98692754]
 [0.83480969 0.99819089 0.99483201]
 [0.07909216 0.53654673 0.65404015]
 [0.78873821 0.99032815 0.9997429 ]]
[0.97463185 1.         0.99819089 0.65404015 0.9997429 ]


array([3, 0, 2])

In [2]:
arr1 = np.random.rand(20,5)
arr = 1-cdist(arr1, arr1, metric = 'cosine')
# print(arr)
mask = np.zeros(arr.shape, dtype=bool)
np.fill_diagonal(arr, 0)
max = np.max(arr, axis = 0)
print(max)
m = max.argsort()
max[m]

[0.96987555 0.93117361 0.99175944 0.94328947 0.94435571 0.95077862
 0.98731626 0.95820886 0.98253808 0.95508419 0.95820886 0.97900068
 0.97631643 0.9662245  0.9409062  0.93504933 0.95508419 0.97900068
 0.99175944 0.98731626]


array([0.93117361, 0.93504933, 0.9409062 , 0.94328947, 0.94435571,
       0.95077862, 0.95508419, 0.95508419, 0.95820886, 0.95820886,
       0.9662245 , 0.96987555, 0.97631643, 0.97900068, 0.97900068,
       0.98253808, 0.98731626, 0.98731626, 0.99175944, 0.99175944])

In [3]:
c = np.random.rand(300, 3)
d = np.random.rand(100, 3)

In [4]:
%timeit cosine_similarity(c,d)
%timeit 1- cdist(c,d, metric = 'cosine')

655 µs ± 27 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
245 µs ± 1.4 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
